[system]
debug_mode = true
process_loop_ms = 30000
pnl_parallel_batch_size = 20

# Data source for transaction data (currently only "BirdEye" is supported)
data_source = "BirdEye"

[multichain]
enabled_chains = ["solana", "ethereum", "base", "bsc"]
default_chain = "solana"

[redis]
url = "redis://localhost:6379"
default_lock_ttl_seconds = 600


# DexScreener configuration for boosted token discovery
[dexscreener]
api_base_url = "https://api.dexscreener.com"
request_timeout_seconds = 30
rate_limit_delay_ms = 1000  # 60 requests per minute = 1 request per second
max_retries = 3
enabled = true
min_boost_amount = 100.0    # Minimum boost amount to consider
max_boosted_tokens = 25     # Limit boosted tokens for quality filtering

[birdeye]
api_key = "5ff313b239ac42e297b830b10ea1871d"
api_base_url = "https://public-api.birdeye.so"
request_timeout_seconds = 30
max_traders_per_token = 100  # Increased from 20 for maximum coverage (doesn't affect BirdEye API limits)
max_transactions_per_trader = 100  # API limit - DO NOT CHANGE
default_max_transactions = 1000  # Default maximum transactions to fetch/analyze per wallet
new_listing_enabled = true
new_listing_min_liquidity = 1000.0
new_listing_max_age_hours = 24
new_listing_max_tokens = 25  # Limit new listings for quality filtering
max_trending_tokens = 25  # Limit trending tokens for quality filtering

# Balance API configuration for real-time wallet balance fetching (fixes phantom buy unrealized P&L bug)
balance_api_enabled = true  # Enable real balance fetching for accurate unrealized P&L
balance_api_timeout_seconds = 15  # Shorter timeout for balance calls
balance_cache_ttl_seconds = 60  # Cache balance data for 1 minute to avoid excessive API calls


# PnL filtering configuration section removed - these were never used in actual P&L processing
# All P&L calculations are performed without filtering based on capital, hold time, trades, or win rate

# Trader filtering for wallet discovery (only these 3 fields are actually used)
[trader_filter]
min_capital_deployed_sol = 0.001   # Minimum capital in SOL
min_total_trades = 2               # Minimum number of trades
min_win_rate = 25.0                # Minimum win rate percentage

[api]
host = "0.0.0.0"
port = 8080

[database]
postgres_url = "postgresql://root:Great222*@localhost:5432/analyser"
enabled = true