[package]
name = "config_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
config = "0.14"
thiserror = "1.0"
anyhow = "1.0"
tracing = "0.1"
regex = "1.10"
serde_json = "1.0"
