[workspace]

[package]
name = "test_redis_integration"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
redis = { version = "0.24", features = ["tokio-comp"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"